name: test-doctr
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - pip
    - pooch
    # Development requirements
    - sphinx
    - sphinx_rtd_theme
    - sphinx-gallery
    - numpydoc
